//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_Minecraft_Blazor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_ItemList {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_ItemList() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SF_Minecraft_Blazor.Resources.Pages_ItemList", typeof(Pages_ItemList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ItemsLoadedSuccessfully {
            get {
                return ResourceManager.GetString("ItemsLoadedSuccessfully", resourceCulture);
            }
        }
        
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        internal static string CannotLoadItemsFromDataSource {
            get {
                return ResourceManager.GetString("CannotLoadItemsFromDataSource", resourceCulture);
            }
        }
        
        internal static string ItemDeleteSuccessfully {
            get {
                return ResourceManager.GetString("ItemDeleteSuccessfully", resourceCulture);
            }
        }
        
        internal static string CannotDeleteItem {
            get {
                return ResourceManager.GetString("CannotDeleteItem", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        internal static string StackSize {
            get {
                return ResourceManager.GetString("StackSize", resourceCulture);
            }
        }
        
        internal static string MaximumDurability {
            get {
                return ResourceManager.GetString("MaximumDurability", resourceCulture);
            }
        }
        
        internal static string EnchantCategories {
            get {
                return ResourceManager.GetString("EnchantCategories", resourceCulture);
            }
        }
        
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        internal static string RepairWith {
            get {
                return ResourceManager.GetString("RepairWith", resourceCulture);
            }
        }
        
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
    }
}
